#### 예외처리란?
정상적인 수행 흐름과 예외 처리 부분을 분리하는 것 

* try : 예외가 발생할 것으로 예상되는 영역
* throw : 예외가 발생할 경우 예외 전달 
* catch : 예외처리 핸들러 

catch(...){}  -> 모든 타입의 값을 처리할 수 있는 예외 처리 핸들러 
이것을 먼저 위치시키면 컴파일에러 발생 


MyException라는 부모를 선언해서 이것을 상속 받는 것들로 처리하면 예외 catch()부분이 더 간단해진다 

````
#include <iostream>

using namespace std;

int n1, n2, n3;

class MyException
{
public:
	virtual void What() = 0; // 추상 클래스로 만듦 
};
class Dividezero : public MyException
{
public:
	void What() { cout << "0으로 나눌 수 없습니다" << endl; }
};

class NegativeNumber : public MyException
{
public:
	void What() { cout << " n1 과 n2는 음수가 될 수 없습니다" << endl; }
};

int main()
{
	cin >> n1 >> n2;

	try
	{
		if (n2 == 0)throw Dividezero();

		if (n1 <= 0 || n2 <= 0) throw NegativeNumber();
		cout << n1 + n2 << endl;
		cout << n1 - n2 << endl;
		cout << n1 * n2 << endl;
		cout << n1 / n2 << endl;
	}
	catch (MyException& ex)   // 부모는 자식을 받을 수 있다 (다형성)
	{
		ex.What();
	}
	catch (...)
	{
		cout << "알 수 없는 예외 발생 " << endl;
	}
	return 0;
}
````
====================













